### ISSUE TITLE
[BUG] MSVC_RUNTIME_LIBRARY in tests

### ISSUE THREAD

**Issue by friendlyanon** [erikzenker/hsm#150]
**Describe the bug**
* The `MSVC_RUNTIME_LIBRARY` property is only [available since CMake 3.15](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html), but I forgot to check this in my PR and the minimum required CMake version in the test CML is 3.14.
* The value of this property is not among the supported set of values.

**To Reproduce**
\-

**Expected behavior**
* The minimum requirement shouldn't be a lie.
* The value of the property (if this property is even necessary) should be valid.

**Additional context**
Is this property even necessary?  
The VS generator for CMake already uses `/MDd` for `Debug` configuration and `/MD` for everything else.  
Is statically linking the CRT for the tests important?

**Comment by erikzenker** [comment]
I am not an expert for msvc. I just added `MSVC_RUNTIME_LIBRARY` to satisfy the compiler and get CI. If we just need to set minimum cmake version to `3.15` that would be okay for me.

**Comment by friendlyanon** [comment]
I just built and ran the tests without the property, I think it can be safely dropped.
