### ISSUE TITLE
[FEATURE] Documentation. More fsm comparison criteria

### ISSUE THREAD

**Issue by heretic13** [erikzenker/hsm#168]
I have a complex state machine (with subs) with several dozen states and transitions. Released on boost::msm.

And I have 2 problems with it:
1. Long compilation time. About 2 minutes for any change of code.
2. The huge amount of memory required by the compiler to compile the given state machine. I saw with my own eyes the consumption of 7 GB of memory at its peak.

I can forgive the lengthy compilation. There are mechanisms that have helped me reduce the need to constantly recompile the state machine.

But the huge amount of memory for the compiler confuses me a lot. This required me to use VS 2022 (in Preview state) and compile a 64-bit application.

I'm in the middle of looking for a finite state machine library with similar functionality to boost::msm, but requiring less memory to compile (less than 4GB).

Please add an approximate comparison of the memory consumed by the compiler when compiling equivalent state machines for the boost::msm and hsm implementations.

**Comment by erikzenker** [comment]
Hi @heretic13 will do

**Comment by erikzenker** [comment]
@heretic13 I added results of the state machine benchmark to the project readme https://github.com/erikzenker/hsm#compilememory-benchmark-results
